### ISSUE TITLE
is column ''anatomy_select'' in the training data a binary one?

### ISSUE THREAD

**Issue by AlkaSaliss** [ramp-kits/autism#17]
hi,
In the starter-kit it's said that the column 'anatomy_select' in the training data is a binary one, pointing to the quality of the data
But when calling a value_counts on it I've values ranging in 0, 1, 2, 3
Have I missed something?
![autism_1](https://user-images.githubusercontent.com/33458274/39820460-27f306c8-53a6-11e8-9aef-a7e919a45770.png)

**Comment by glemaitre** [comment]
Thanks to pointing this out. We need to update the starting-kit. The QC has been done with more granularity:

* 2: passing the QC with reserves
* 1: passing the QC
* 0 and 3: not passing the QC
