### ISSUE TITLE
Pre-requisite: ramp_test_workflow

### ISSUE THREAD

**Issue by ncordier** [ramp-kits/autism#23]
On [the webpage](https://indico.lal.in2p3.fr/event/4845/), `ramp_test_workflow` is mentioned.

![ramp test workflow](https://i.imgur.com/3rc4sEF.png)

However, I am not sure whether _executing this workflow_ is actually running the Jupyter notebook, executing `ramp_test_submission` at the end of the notebook, or executing something else which would be found in the [Ramp-Worflow](https://github.com/paris-saclay-cds/ramp-workflow) repository.

**Comment by ncordier** [comment]
It has to be `ramp_test_submission` since the auto-completion only suggests these:

![autocompletion](https://i.imgur.com/NZivHQ2.png)

**Comment by kegl** [comment]
`ramp_test_submission` is a standalone script that tests your python files in `submissions/starting_kit/`. It's a "unit test" that you should use to check that your submission files are correct.

**Comment by kegl** [comment]
You can read about what happens behind the scene in the [ramp-workflow wiki[(https://github.com/paris-saclay-cds/ramp-workflow/wiki/Build-your-own-workflow)

**Comment by ncordier** [comment]
> Typical workflows are a single classifier or a feature extractor followed by a classifier used here, but we have more complex workflows.

I I understand it right, a submission is expected to contain a workflow, i.e. a feature extractor and a classifier.

So, to come back to my initial question, `ramp_test_workflow`, which is mentioned in the `Prerequisites` section on [this webpage](https://indico.lal.in2p3.fr/event/4845/), is actually a **typo**: it should be `ramp_test_submission`, right?

**Comment by kegl** [comment]
Yes, it was a typo, thanks for spotting this, I corrected it.
