### ISSUE TITLE
Is Keras (or any DL framework) installed in the server ?

### ISSUE THREAD

**Issue by fahd09** [ramp-kits/autism#25]
I am thinking of using a DL framework but I am wondering if using such framework is allowed or installed on the server.

**Comment by kegl** [comment]
We add libraries as you use them. We have experience with keras/tensorflow and pytorch, if somebody submits with those, we'll add them to the backend. In general, we will add any open source library you'd like to use.

**Comment by JeanClaudeR** [comment]
If I understand it correctly, we are restricted to CPU versions, since the instances are CPU only.
Did I miss something ?

**Comment by kegl** [comment]
No you didn't. CPU only.

**Comment by glemaitre** [comment]
Refer to #5. Ping us if an open-source library is missing.
