### ISSUE TITLE
Does the test server have SPM, FSL statistical packages?

### ISSUE THREAD

**Issue by suprsankr** [ramp-kits/autism#27]
Will the above statistical packages be available on the test server or statistical testing tools have to be installed locally for (structural) anatomical feature analysis/extraction ?

**Comment by kegl** [comment]
Please give us instruction on how to install.

**Comment by GaelVaroquaux** [comment]
SPM requires matlab, so we will not be able to install it.

But how are you planning to use them? Anatomical features have already been extracted.

**Comment by suprsankr** [comment]
@GaelVaroquaux  i was wondering if statistical tests need to be run on the anatomical features.

**Comment by glemaitre** [comment]
@suprsankr This is one of the strategy that you can use to make some feature selection. You can refer to [scikit-learn feature selection module](http://scikit-learn.org/stable/modules/feature_selection.html) documentation

**Comment by glemaitre** [comment]
Closing this issue. Refer to #5 for additional package to be installed.

**Comment by suprsankr** [comment]
@glemaitre thank you! :)
