### ISSUE TITLE
FeatureExtractor() inside cross_validation

### ISSUE THREAD

**Issue by zh1peng** [ramp-kits/autism#35]
When I did some feature selection process in FeatureExtractor() or Classifier() based on some relationship between X and y. I realized different X_split and y_split in each cv fold make the selected features different for each cv fold. This gives different auc. So I was thinking would it be better for the FeatureExtractor() outside of cross_validation? 
Something like:
```python
    features=FeatureExtractor()
    X_new=features.fit_transform(X,y)
    cross_validate(Classifier(), X_new, y)
```
Not hundred sure about this. Maybe if the feature selection is stable enough, then the variance from this could be ignored.

When I tried to build FC maps with motion regressed out and compute the graph measures for the FC, it took 10 mins to finish the feature extraction. If the FeatureExtractor() is outside the cross_validation process, it would save a lot of time. This is just a small issue as I gave up building FC myself and calculating graph.

**Comment by glemaitre** [comment]
> So I was thinking would it be better for the FeatureExtractor() outside of cross_validation

Be aware that you are going to make a selection on the full public data set. If the features are noisy, you are almost certain to overfit the public data set and get really bad results on the private set.

You can refer on the [following example](http://scikit-learn.org/stable/auto_examples/model_selection/plot_nested_cross_validation_iris.html#sphx-glr-auto-examples-model-selection-plot-nested-cross-validation-iris-py) which shows nested cross-validation which could be used to make such selection and hyperparameters exploration.
