### ISSUE TITLE
update h5py module at the server 

### ISSUE THREAD

**Issue by SaeedFarahani** [ramp-kits/autism#42]
please update h5py  module at the server,
because I get this "training_error" and I don't know what is reason. It works at local test.
I hop to solve it with update of h5py module.
can you help me to solve it with some else solutions ?
 
![image](https://user-images.githubusercontent.com/15821182/41699810-e6e29782-753a-11e8-8ae2-91ae16dd461c.png)
 @GaelVaroquaux

**Comment by kegl** [comment]
This error is explained in this issue. 
https://github.com/ramp-kits/autism/issues/32

**Comment by jorisvandenbossche** [comment]
Just to be clear, this has nothing to do with `h5py` (what you see is only a warning), but is related to the error at the end of your log output:

```
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'save-y-preds'
```

and that is explained in https://github.com/ramp-kits/autism/issues/32#issuecomment-395955406
