### ISSUE TITLE
Regarding preprocessing

### ISSUE THREAD

**Issue by jc4816** [ramp-kits/autism#46]
Hi,

I am working on the competition data after attended the challenge. May I ask a quick question regarding preprocessing? Do you mind specify what kind of preprocessing you did for rs-fMRI and T1 (especially for rs-fMRI)? For example, specific parameters for slice timing, realignment, registration, smoothing, frequency band, etc.

Looking forward to hearing from you. Thanks a lot!

Best,
Jongwoo Choi

**Comment by glemaitre** [comment]
The script of the fMRI extraction is available there:
https://github.com/ramp-kits/autism/blob/master/preprocessing/extract_time_series.py

You can refer to the nilearn documentation for the internal of the functions.

**Comment by jc4816** [comment]
Hi,

Thanks for the reply. 
We checked the code In `extract_time_series.py`, and found that input image is 'session_1/rest_1/rest_res2standard.nii.gz', which means you already preprocessed the data (normalized to MNI space). What kind of procedure did you include (e.g., slice timing, realignment, registration, smoothing) when you preprocess this data, i.e., how did you generate PATH_TO_RESTING_STATE = 'session_1/rest_1/rest_res2standard.nii.gz' ?


Best,
Jongwoo Choi

**Comment by glemaitre** [comment]
You are right. We did not make the scripts available.
We are going to do that soon.
You can check the progress of #47.

**Comment by glemaitre** [comment]
The PR with the scripts have been merged.
