### ISSUE TITLE
best submissions

### ISSUE THREAD

**Issue by ntraut** [ramp-kits/autism#62]
How should we deal with the `best_submission` branch?
Should we keep it as an independent branch and merge master into it or merge it to the master branch?

Also, two of the best submissions now fail because of scikit-learn `LogisticRegression` classifier evolution. Should we freeze scikit-learn version in order to maintain compatibility?

**Comment by glemaitre** [comment]
> Also, two of the best submissions now fail because of scikit-learn LogisticRegression classifier evolution. Should we freeze scikit-learn version in order to maintain compatibility?

I think it should be best to pin the version of the library.

**Comment by ntraut** [comment]
I was not suggesting to freeze the development of scikit learn if that was what you thought, I was suggesting something more like pinning the version of the library, so I think we agree ;). (I froze sckit learn version in the files requirements.txt and environment.yml in commit 171c621542a8527d20bfb79f916e1a6f3f8c55d6)

**Comment by glemaitre** [comment]
> I was not suggesting to freeze the development of scikit learn if that was what you thought, I was suggesting something more like pinning the version of the library, so I think we agree ;)

It was what I understood :) Yep everything is fine.
